# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataframe.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dataframe.proto',
  package='skl',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x64\x61taframe.proto\x12\x03skl\"\xbd\x01\n\x0e\x44\x61taFrameProto\x12\'\n\x05shape\x18\x01 \x01(\x0b\x32\x18.skl.DataFrameShapeProto\x12\x31\n\x07\x63olumns\x18\x02 \x03(\x0b\x32 .skl.DataFrameProto.ColumnsEntry\x12\r\n\x05index\x18\x03 \x03(\x03\x1a@\n\x0c\x43olumnsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.skl.ColumnProto:\x02\x38\x01\"8\n\x13\x44\x61taFrameShapeProto\x12\x0e\n\x06n_rows\x18\x01 \x01(\x05\x12\x11\n\tn_columns\x18\x02 \x01(\x05\"\x94\x01\n\x0b\x43olumnProto\x12\x1c\n\x05\x64type\x18\x01 \x01(\x0e\x32\r.skl.DataType\x12\x0e\n\x06n_rows\x18\x02 \x01(\x05\x12\x16\n\ndouble_val\x18\x03 \x03(\x01\x42\x02\x10\x01\x12\x15\n\tint64_val\x18\x04 \x03(\x03\x42\x02\x10\x01\x12\x12\n\nstring_val\x18\x05 \x03(\t\x12\x14\n\x08\x62ool_val\x18\x06 \x03(\x08\x42\x02\x10\x01*S\n\x08\x44\x61taType\x12\x0e\n\nDT_INVALID\x10\x00\x12\r\n\tDT_DOUBLE\x10\x01\x12\x0c\n\x08\x44T_INT64\x10\x02\x12\r\n\tDT_STRING\x10\x03\x12\x0b\n\x07\x44T_BOOL\x10\x04\x42\x03\xf8\x01\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='skl.DataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DT_INVALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DT_DOUBLE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DT_INT64', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DT_STRING', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DT_BOOL', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=425,
  serialized_end=508,
)
_sym_db.RegisterEnumDescriptor(_DATATYPE)

DataType = enum_type_wrapper.EnumTypeWrapper(_DATATYPE)
DT_INVALID = 0
DT_DOUBLE = 1
DT_INT64 = 2
DT_STRING = 3
DT_BOOL = 4



_DATAFRAMEPROTO_COLUMNSENTRY = _descriptor.Descriptor(
  name='ColumnsEntry',
  full_name='skl.DataFrameProto.ColumnsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='skl.DataFrameProto.ColumnsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='skl.DataFrameProto.ColumnsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=214,
)

_DATAFRAMEPROTO = _descriptor.Descriptor(
  name='DataFrameProto',
  full_name='skl.DataFrameProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape', full_name='skl.DataFrameProto.shape', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='columns', full_name='skl.DataFrameProto.columns', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index', full_name='skl.DataFrameProto.index', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DATAFRAMEPROTO_COLUMNSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=214,
)


_DATAFRAMESHAPEPROTO = _descriptor.Descriptor(
  name='DataFrameShapeProto',
  full_name='skl.DataFrameShapeProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n_rows', full_name='skl.DataFrameShapeProto.n_rows', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n_columns', full_name='skl.DataFrameShapeProto.n_columns', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=272,
)


_COLUMNPROTO = _descriptor.Descriptor(
  name='ColumnProto',
  full_name='skl.ColumnProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dtype', full_name='skl.ColumnProto.dtype', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n_rows', full_name='skl.ColumnProto.n_rows', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='double_val', full_name='skl.ColumnProto.double_val', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='int64_val', full_name='skl.ColumnProto.int64_val', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='string_val', full_name='skl.ColumnProto.string_val', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bool_val', full_name='skl.ColumnProto.bool_val', index=5,
      number=6, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=423,
)

_DATAFRAMEPROTO_COLUMNSENTRY.fields_by_name['value'].message_type = _COLUMNPROTO
_DATAFRAMEPROTO_COLUMNSENTRY.containing_type = _DATAFRAMEPROTO
_DATAFRAMEPROTO.fields_by_name['shape'].message_type = _DATAFRAMESHAPEPROTO
_DATAFRAMEPROTO.fields_by_name['columns'].message_type = _DATAFRAMEPROTO_COLUMNSENTRY
_COLUMNPROTO.fields_by_name['dtype'].enum_type = _DATATYPE
DESCRIPTOR.message_types_by_name['DataFrameProto'] = _DATAFRAMEPROTO
DESCRIPTOR.message_types_by_name['DataFrameShapeProto'] = _DATAFRAMESHAPEPROTO
DESCRIPTOR.message_types_by_name['ColumnProto'] = _COLUMNPROTO
DESCRIPTOR.enum_types_by_name['DataType'] = _DATATYPE

DataFrameProto = _reflection.GeneratedProtocolMessageType('DataFrameProto', (_message.Message,), dict(

  ColumnsEntry = _reflection.GeneratedProtocolMessageType('ColumnsEntry', (_message.Message,), dict(
    DESCRIPTOR = _DATAFRAMEPROTO_COLUMNSENTRY,
    __module__ = 'dataframe_pb2'
    # @@protoc_insertion_point(class_scope:skl.DataFrameProto.ColumnsEntry)
    ))
  ,
  DESCRIPTOR = _DATAFRAMEPROTO,
  __module__ = 'dataframe_pb2'
  # @@protoc_insertion_point(class_scope:skl.DataFrameProto)
  ))
_sym_db.RegisterMessage(DataFrameProto)
_sym_db.RegisterMessage(DataFrameProto.ColumnsEntry)

DataFrameShapeProto = _reflection.GeneratedProtocolMessageType('DataFrameShapeProto', (_message.Message,), dict(
  DESCRIPTOR = _DATAFRAMESHAPEPROTO,
  __module__ = 'dataframe_pb2'
  # @@protoc_insertion_point(class_scope:skl.DataFrameShapeProto)
  ))
_sym_db.RegisterMessage(DataFrameShapeProto)

ColumnProto = _reflection.GeneratedProtocolMessageType('ColumnProto', (_message.Message,), dict(
  DESCRIPTOR = _COLUMNPROTO,
  __module__ = 'dataframe_pb2'
  # @@protoc_insertion_point(class_scope:skl.ColumnProto)
  ))
_sym_db.RegisterMessage(ColumnProto)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\370\001\001'))
_DATAFRAMEPROTO_COLUMNSENTRY.has_options = True
_DATAFRAMEPROTO_COLUMNSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_COLUMNPROTO.fields_by_name['double_val'].has_options = True
_COLUMNPROTO.fields_by_name['double_val']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_COLUMNPROTO.fields_by_name['int64_val'].has_options = True
_COLUMNPROTO.fields_by_name['int64_val']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_COLUMNPROTO.fields_by_name['bool_val'].has_options = True
_COLUMNPROTO.fields_by_name['bool_val']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
