# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predict.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import dataframe_pb2 as dataframe__pb2
import model_pb2 as model__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='predict.proto',
  package='skl',
  syntax='proto3',
  serialized_pb=_b('\n\rpredict.proto\x12\x03skl\x1a\x0f\x64\x61taframe.proto\x1a\x0bmodel.proto\"[\n\x11PredictionRequest\x12\"\n\nmodel_spec\x18\x01 \x01(\x0b\x32\x0e.skl.ModelSpec\x12\"\n\x05input\x18\x02 \x01(\x0b\x32\x13.skl.DataFrameProto\"\xa9\x01\n\x12PredictionResponse\x12,\n\x0fprediction_spec\x18\x01 \x01(\x0b\x32\x13.skl.PredictionSpec\x12\x35\n\x07outputs\x18\x02 \x03(\x0b\x32$.skl.PredictionResponse.OutputsEntry\x1a.\n\x0cOutputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\x8d\x01\n\x0ePredictionSpec\x12\x11\n\tn_classes\x18\x01 \x01(\x05\x12\x11\n\tcache_hit\x18\x02 \x01(\x08\x12\x16\n\x0e\x65xecution_time\x18\x03 \x01(\x03\x12\x13\n\x0b\x63lass_names\x18\x04 \x03(\t\x12\x16\n\x0epositive_class\x18\x05 \x01(\t\x12\x10\n\x08model_id\x18\x06 \x01(\tB\x03\xf8\x01\x01\x62\x06proto3')
  ,
  dependencies=[dataframe__pb2.DESCRIPTOR,model__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PREDICTIONREQUEST = _descriptor.Descriptor(
  name='PredictionRequest',
  full_name='skl.PredictionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_spec', full_name='skl.PredictionRequest.model_spec', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input', full_name='skl.PredictionRequest.input', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=143,
)


_PREDICTIONRESPONSE_OUTPUTSENTRY = _descriptor.Descriptor(
  name='OutputsEntry',
  full_name='skl.PredictionResponse.OutputsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='skl.PredictionResponse.OutputsEntry.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='skl.PredictionResponse.OutputsEntry.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=315,
)

_PREDICTIONRESPONSE = _descriptor.Descriptor(
  name='PredictionResponse',
  full_name='skl.PredictionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prediction_spec', full_name='skl.PredictionResponse.prediction_spec', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='skl.PredictionResponse.outputs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PREDICTIONRESPONSE_OUTPUTSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=315,
)


_PREDICTIONSPEC = _descriptor.Descriptor(
  name='PredictionSpec',
  full_name='skl.PredictionSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n_classes', full_name='skl.PredictionSpec.n_classes', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cache_hit', full_name='skl.PredictionSpec.cache_hit', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='execution_time', full_name='skl.PredictionSpec.execution_time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='class_names', full_name='skl.PredictionSpec.class_names', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='positive_class', full_name='skl.PredictionSpec.positive_class', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_id', full_name='skl.PredictionSpec.model_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=459,
)

_PREDICTIONREQUEST.fields_by_name['model_spec'].message_type = model__pb2._MODELSPEC
_PREDICTIONREQUEST.fields_by_name['input'].message_type = dataframe__pb2._DATAFRAMEPROTO
_PREDICTIONRESPONSE_OUTPUTSENTRY.containing_type = _PREDICTIONRESPONSE
_PREDICTIONRESPONSE.fields_by_name['prediction_spec'].message_type = _PREDICTIONSPEC
_PREDICTIONRESPONSE.fields_by_name['outputs'].message_type = _PREDICTIONRESPONSE_OUTPUTSENTRY
DESCRIPTOR.message_types_by_name['PredictionRequest'] = _PREDICTIONREQUEST
DESCRIPTOR.message_types_by_name['PredictionResponse'] = _PREDICTIONRESPONSE
DESCRIPTOR.message_types_by_name['PredictionSpec'] = _PREDICTIONSPEC

PredictionRequest = _reflection.GeneratedProtocolMessageType('PredictionRequest', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTIONREQUEST,
  __module__ = 'predict_pb2'
  # @@protoc_insertion_point(class_scope:skl.PredictionRequest)
  ))
_sym_db.RegisterMessage(PredictionRequest)

PredictionResponse = _reflection.GeneratedProtocolMessageType('PredictionResponse', (_message.Message,), dict(

  OutputsEntry = _reflection.GeneratedProtocolMessageType('OutputsEntry', (_message.Message,), dict(
    DESCRIPTOR = _PREDICTIONRESPONSE_OUTPUTSENTRY,
    __module__ = 'predict_pb2'
    # @@protoc_insertion_point(class_scope:skl.PredictionResponse.OutputsEntry)
    ))
  ,
  DESCRIPTOR = _PREDICTIONRESPONSE,
  __module__ = 'predict_pb2'
  # @@protoc_insertion_point(class_scope:skl.PredictionResponse)
  ))
_sym_db.RegisterMessage(PredictionResponse)
_sym_db.RegisterMessage(PredictionResponse.OutputsEntry)

PredictionSpec = _reflection.GeneratedProtocolMessageType('PredictionSpec', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTIONSPEC,
  __module__ = 'predict_pb2'
  # @@protoc_insertion_point(class_scope:skl.PredictionSpec)
  ))
_sym_db.RegisterMessage(PredictionSpec)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\370\001\001'))
_PREDICTIONRESPONSE_OUTPUTSENTRY.has_options = True
_PREDICTIONRESPONSE_OUTPUTSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
